version: '3.8'
services:
  db:
    image: postgres:15.1-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: song-db
    ports:
      - '5433:5432'
    volumes:
      - song-db-data:/var/lib/postgresql/data
volumes:
  song-db-data:
    driver: local
