version: '3.8'

services:
  song-db:
    image: postgres:15.1-alpine
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - '5433:5432'
    volumes:
      - song-db-data:/var/lib/postgresql/data
    networks:
      - resource-network
volumes:
  song-db-data:
    driver: local
networks:
  resource-network:
    external:
      name: resource-network
